CarDealership/CarDealership/Controllers/BrandController.cs
using CarDealership.Data;
using CarDealership.Models.BrandViewModels;
using CarDealership.Services.Brand;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Authorize(Roles = "Admin")]
public class BrandController : Controller
{
    private readonly IBrandService _brandService;

    public BrandController(IBrandService brandService)
    {
        _brandService = brandService;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var brands = await _brandService.GetAllBrandsAsync();
        return View(brands);
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create( CreateBrandViewModel brandViewModel)
    {
        if (ModelState.IsValid)
        {
            await _brandService.CreateBrandAsync(brandViewModel);
            return RedirectToAction(nameof(Index));
        }
        return View(brandViewModel);
    }

    [HttpGet]
    public async Task<IActionResult> Edit(EditBrandViewModel editBrandViewModel)
    {
        if (editBrandViewModel.Id == null)
        {
            return NotFound();
        }

        editBrandViewModel.Brand = await _brandService.GetBrandByIdAsync(editBrandViewModel.Id.Value);
        if (editBrandViewModel.Brand == null)
        {
            return NotFound();
        }

        return View(editBrandViewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> EditPost(EditBrandViewModel editBrandViewModel)
    {

        if (ModelState.IsValid)
        {
            var isSuccess = await _brandService.UpdateBrandAsync(editBrandViewModel);
            if (isSuccess)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }
        return View("Edit",editBrandViewModel);
    }

    private async Task<bool> BrandExists(int id)
    {
        return await _brandService.BrandExistsAsync(id);
    }
}

CarDealership/CarDealership/Controllers/ColorController.cs
using Microsoft.AspNetCore.Mvc;
using CarDealership.Data;
using Microsoft.AspNetCore.Authorization;
using CarDealership.Services.Color;
using CarDealership.Models.ColorViewModels;

[Authorize(Roles = "Admin")]
public class ColorController : Controller
{
    private readonly IColorService _carColorService;

    public ColorController(IColorService carColorService)
    {
        _carColorService = carColorService;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var colors = await _carColorService.GetAllCarColorsAsync();
        return View(colors);
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CreateColorViewModel createCarColorViewModel)
    {
        if (ModelState.IsValid)
        {
            await _carColorService.CreateCarColorAsync(createCarColorViewModel);
            return RedirectToAction(nameof(Index));
        }

        return View(createCarColorViewModel);
    }

    [HttpGet]
    public async Task<IActionResult> Edit(EditColorViewModel editColorViewModel)
    {
        if (editColorViewModel.Id == null)
        {
            return NotFound();
        }

         editColorViewModel.CarColor = await _carColorService.GetCarColorByIdAsync(editColorViewModel.Id.Value);

        if (editColorViewModel.CarColor == null)
        {
            return NotFound();
        }

        return View(editColorViewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> EditPost(EditColorViewModel editColorViewModel)
    {

        if (ModelState.IsValid)
        {
            var isSuccess = await _carColorService.UpdateCarColorAsync(editColorViewModel);
            if (isSuccess)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }

        return View("Edit",editColorViewModel);
    }

    private async Task<bool> ColorExists(int id)
    {
        return await _carColorService.CarColorExistsAsync(id);
    }
}

CarDealership/CarDealership/Controllers/ModelController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CarDealership.Data;
using Microsoft.AspNetCore.Authorization;
using CarDealership.Services.Model;
using CarDealership.Models.ModelViewModels;

[Authorize(Roles = "Admin")]
public class ModelController : Controller
{
    private readonly IModelService _modelService;

    public ModelController(IModelService modelService)
    {
        _modelService = modelService;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var modelsByBrand = await _modelService.GetModelsGroupedByBrandAsync();
        return View(modelsByBrand);
    }

    [HttpGet]
    public async Task<IActionResult> Create()
    {
        ViewBag.Brands = await _modelService.GetAllBrandsAsync();
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CreateModelViewModel createModelViewModel)
    {
        if (ModelState.IsValid)
        {
            await _modelService.CreateModelAsync(createModelViewModel);
            return RedirectToAction(nameof(Index));
        }

        ViewBag.Brands = await _modelService.GetAllBrandsAsync();
        return View(createModelViewModel);
    }

    [HttpGet]
    public async Task<IActionResult> Edit(EditModelViewModel editModelViewModel)
    {
        if (editModelViewModel.Id == null)
        {
            return NotFound();
        }

        editModelViewModel.Model = await _modelService.GetModelByIdAsync(editModelViewModel.Id.Value);
        if (editModelViewModel.Model == null)
        {
            return NotFound();
        }

        ViewBag.Brands = await _modelService.GetAllBrandsAsync();
        return View("Edit",editModelViewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> EditPost(EditModelViewModel editModelViewModel)
    {
        if (ModelState.IsValid)
        {
            var isSuccess = await _modelService.UpdateModelAsync(editModelViewModel);
            if (isSuccess)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }

        ViewBag.Brands = await _modelService.GetAllBrandsAsync();
        return View(editModelViewModel);
    }

    private async Task<bool> ModelExists(int id)
    {
        return await _modelService.ModelExistsAsync(id);
    }
}

CarDealership/CarDealership/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarDealership</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CarDealership.styles.css" asp-append-version="true" />
</head>
<body class="mb-0">
    <header style="background: rgb(255,255,255);
background: linear-gradient(0deg, rgba(255,255,255,0.9921102229954482) 0%, rgba(95,105,116,0.28622787005427175) 100%);">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light ">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="../../../Images/CarDealershipLogo.png" style="width:60px;height:60px;" />
                    <strong>АвтоПлаза</strong>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="AdminCar" asp-action="Index">Коли</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Brand" asp-action="Index">Марки</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Model" asp-action="Index">Модели</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Color" asp-action="Index">Цветове</a>
                            </li>

                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="pb-3" style=" overflow-x: hidden;">
        @RenderBody()
    </main>

    <footer class="text-muted" style="background: rgb(95,105,116);
background: linear-gradient(0deg, rgba(95,105,116,1) 0%, rgba(255,255,255,0.9640990185136554) 100%);">
        <div class="container">
            <div class="row">
                <div class="d-flex justify-content-center mt-5">
                    <p class="text-white"><strong>© 2024 – АвтоПлаза. Всички права запазени.</strong></p>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>